### ISSUE TITLE
NRE when using the library in .NET console project created with pre dotnet core project template

### ISSUE THREAD

**Issue by nicky-iliev** [riskfirst/riskfirst.hateoas#10]
I created a console app using a pre dotnet core project template. Added MVC core deps and run it.
There is a NRE inside DefaultRouteMap ctor - DependencyContext.Default is null.

There is a hack for initializing the DependencyContext.Default (if you supply a App.deps.json (copied from .net core application))

**Comment by jamiecoh** [comment]
Fixed by #11
