### ISSUE TITLE
Breaking Change Introduced in v1.2.0

### ISSUE THREAD

**Issue by adamrodger** [riskfirst/riskfirst.hateoas#13]
v1.1.3 of the NuGet package has the minimum requirements of .Net 4.5.1 and .Net Standard 1.6.

v1.2.0 has the minimum requirements of .Net 4.6.1 and .Net Standard 2.0.

This is a breaking change because you've dropped support for older (and still widely used!) platforms and so the version number of the package should have been incremented to v2.0 as per SemVer 2.0 rules.

**Comment by coldridj** [comment]
You're absolutely correct. I will update the version and get the 1.2.0 package unlisted on nuget.org. 

If you/users are interested in continuing maintenance of a net451/netstandard1.6 branch we will look at the feasibility as and when future code changes are introduced.
