### ISSUE TITLE
Property name, "_links" verus "links". Configurable?

### ISSUE THREAD

**Issue by rebeccapowell** [riskfirst/riskfirst.hateoas#15]
It seems that HATEOAS has no defined preference for the use of "links" or "_links". Some libraries use one or the other.

As part of our API definition, we have published the contracts using "links" but this library uses "_lnks" as the property name. I don't really want to change the contract since customer have already started building clients against that published contract.

Is there any way to configure this property name?

**Comment by jamiecoh** [comment]
Hi, 

Our default implementation has a base model class implementing `ILinkContainer` which does indeed hard-code the property to `_links`. 

There is nothing stopping you having your own base model which implements `ILinkContainer` but uses whatever property you like. Or you can just implement `ILinkContainer` in your existing model(s).

Let me know if you have any further questions.

Regards

Jamie
