### ISSUE TITLE
Cannot add pagelinks, getting NullReferenceException

### ISSUE THREAD

**Issue by snippetkid** [riskfirst/riskfirst.hateoas#19]
While trying to call `linksService.AddLinksAsync(result)` I am getting NullReferenceException.

at RiskFirst.Hateoas.DefaultRouteMap.GetCurrentRoute()
   at RiskFirst.Hateoas.DefaultLinksService.<AddLinksAsync>d__8`1.MoveNext()

Is there a documentation where it shows an example of using page links?

**Comment by jamiecoh** [comment]
Almost all of the samples in https://github.com/riskfirst/riskfirst.hateoas/tree/master/Samples show using `AddLinksAsync`. If you can share more of your project I can take a look at your issue.
