### ISSUE TITLE
ActionContext.RouteData.Routers is empty in AspCore 2.2

### ISSUE THREAD

**Issue by hannan-gc** [riskfirst/riskfirst.hateoas#21]
ActionContext.RouteData.Routers is empty is aspcore 2.2.

Alternative is to use LinkGenerator to for [UrlGeneration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-2.2#url-generation)

I've added a [PR](https://github.com/riskfirst/riskfirst.hateoas/pull/20) to solve that.

Regards,
Hannan

**Comment by jamiecoh** [comment]
Many thanks. It is now merged
