### ISSUE TITLE
Multiple route attribute in same name is not supported while configuring for the HATEOAS library

### ISSUE THREAD

**Issue by rajamadhu** [riskfirst/riskfirst.hateoas#23]
<p>Scenerio:&nbsp;</p>
<p>[HttpGet("~/areas/location/{id:int}", Name = "Get Locations")]&nbsp; //Here&nbsp; Name attribute is same as below route also.</p>
<p>[HttpGet("~/location/{id:int}", Name = "Get Locations")]&nbsp; //route name aslo same ("Get Locations")</p>
<p>public async Task&lt;IActionResult&gt; Getlocation(int id)</p>
<p>{&nbsp; &nbsp; &nbsp;</p>
<p>&nbsp;_linksService.AddLinksAsync(locationmodel);&nbsp; &nbsp; &nbsp;</p>
<p>// Already we have&nbsp; &nbsp; &nbsp;</p>
<p>&nbsp;}</p>
<p>we are aware that , route Name attribute cannot be support same name with more than one route.<br />Expected:&nbsp;</p>
<p>[HttpGet("~/areas/location/{id:int}")]&nbsp; //-- Here We will remove that Name attribute and instead of that we will pass that text in another parameter as below stated.[HttpGet("~/location/{id:int}")]</p>
<p>public async Task&lt;IActionResult&gt; Getlocation(int id)</p>
<p>{&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
<p>&nbsp; &nbsp; _linksService.AddLinksAsync(locationmodel,"Get Locations");&nbsp; &nbsp;</p>
<p>&nbsp; // Possible to pass Rel info&nbsp;&nbsp; (Or)</p>
<p>_linksService.AnotherExtensionMethod(locationmodel,"Get Locations");&nbsp; &nbsp; &nbsp;</p>
<p>// Possible to pass Rel info&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
<p>}&nbsp;&nbsp;&nbsp;</p>
<p>&nbsp;</p>
<p>Also, I have configured the Startup like below:</p>
<p>services.AddLinks(config =&gt;<br />{<br /> config.UseRelativeHrefs();<br /> config.ConfigureRelTransformation(transform =&gt; transform.Add(ctx =&gt; $"{ctx.LinkSpec.RouteName}"));<br /> <br /> config.AddPolicy&lt;Location&gt;("LocationsPolicy", policy =&gt;<br /> {<br /> policy.RequireRoutedLink("users", "Get Locations", x =&gt; new { id = x.Id });</p>
<p>});<br />});</p>
<p><br /> Output :<br />"_links": {<br /> "users": {<br /> "rel": "Get Locations",<br /> "href": "/api/locations/1/users",<br /> "method": "GET"<br /> }</p>
<p>Problem: In this case i have to create indivitual policy for each action methods.&nbsp; N number of actions are there(with same name).</p>
<p>Can someone throw more light on how to resolve the issue?<br /> <br />Your help is much appreciated</p>

**Comment by jamiecoh** [comment]
This is not an enhancement I would make. If you want to submit a pull request for it, please feel free and I'll merge it in if appropriate. I would want to see tests covering the scenario.
