### ISSUE TITLE
DefaultRouteMap doesn't work when integration testing

### ISSUE THREAD

**Issue by adamrodger** [riskfirst/riskfirst.hateoas#7]
In `DefaultRouteMap`, the routes are discovered using `Assembly.GetExecutingAssembly()` and then searching for types which extend `Controller`.

However, when you are performing an integration test using `Microsoft.AspNetCore.TestHost` (as recommended by Microsoft [here](https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing)) then the 'executing' assembly is actually the test assembly, not the service assembly. This means the routes in the service assembly are never discovered and so custom link policies are never applied.

**Comment by jamiecoh** [comment]
I was never particularly happy with this way of mapping the Api. But as I never had a specific issue with it, I never got round to improving that. Using `ApiExplorer` may be one option, but it will take some thought.

If you have any ideas, please feel free to suggest them, either here or in a pull request.

**Comment by adamrodger** [comment]
I have a similar problem in my application where a helper library needs to reflect over types in the real service library to register them, and I do something like (a bit pseudo-codey):

```chsarp
var thisAssembly = typeof(MyClass).GetTypeInfo().Assembly.GetName().Name;
var IEnumerable<CompilationLibrary> libraries =
    DependencyContext.Default
                     .CompileLibraries                      
                     .Where(l => l.Dependencies.Any(d => d.Name.Equals(thisAssembly)));

var names = libraries.Select(l => l.Name).Distinct();
var assemblies = names.Select(a => Assembly.Load(new AssemblyName(a)));
```

Then `assemblies` is the collection of assemblies which directly reference your assembly, so you can loop over them and check their types.

**Comment by jamiecoh** [comment]
That seems sensible. I'll not get a chance to test this out until the weekend/early next week. Feel free to submit a pull if you need it quicker than that.

**Comment by jamiecoh** [comment]
I have made this change and added an integration test project to the [BasicSample](https://github.com/riskfirst/riskfirst.hateoas/tree/master/Samples/RiskFirst.Hateoas.BasicSample) solution. 
Thanks again for your feedback.
